version: '3.7'
services:
    web:
        build: './build/php/'
        ports:
            - "90:80"
        volumes:
            - ./app:/var/www/html
        links:
            - db:db
    db:
        build: './build/mysql/'
        volumes:
            - ~/.docker/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=thisisapassworddamned
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8181:80"
        links:
            - db:db
      