version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volume:
      - ./app:var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD: "super-mot-de-pass-off-doom"
      - MYSQL_DATABASE: "my-first-database"
    volumes:
      - dbData:  '/var/lib/mysql'
  volumes:
    app:
    dbData:
